/**
 * Generates a smart session title based on the first few user messages
 * @param messages Array of user messages (first 2-3 messages)
 * @returns A readable title for the session
 */
export function generateSessionTitle(messages: string[]): string {
  if (!messages || messages.length === 0) {
    return 'Untitled Chat';
  }

  // Take first 2-3 messages and join them
  const firstMessages = messages.slice(0, 3);
  const combinedText = firstMessages.join(' ').toLowerCase();

  // Simple keyword-based title generation
  const title = generateTitleFromKeywords(combinedText);
  
  // Truncate to ~50 characters for neat sidebar display
  return title.length > 50 ? title.substring(0, 47) + '...' : title;
}

/**
 * Generates a title based on keywords in the text
 * @param text Combined text from first few messages
 * @returns A readable title
 */
function generateTitleFromKeywords(text: string): string {
  // Common topics and their associated keywords
  const topicKeywords: Record<string, string[]> = {
    'Productivity': ['productivity', 'efficient', 'time management', 'workflow', 'routine', 'schedule', 'planning'],
    'Learning': ['learn', 'study', 'education', 'course', 'book', 'reading', 'knowledge', 'skill'],
    'Health': ['health', 'fitness', 'exercise', 'workout', 'diet', 'nutrition', 'wellness', 'gym'],
    'Business': ['business', 'marketing', 'strategy', 'startup', 'entrepreneur', 'sales', 'growth'],
    'Technology': ['tech', 'programming', 'code', 'software', 'app', 'development', 'computer'],
    'Finance': ['money', 'finance', 'investment', 'budget', 'saving', 'financial', 'wealth'],
    'Relationships': ['relationship', 'dating', 'marriage', 'family', 'friends', 'social'],
    'Creativity': ['creative', 'art', 'design', 'writing', 'music', 'inspiration', 'ideas'],
    'Travel': ['travel', 'vacation', 'trip', 'destination', 'explore', 'adventure'],
    'Cooking': ['cook', 'recipe', 'food', 'meal', 'kitchen', 'cooking', 'chef']
  };

  // Find the most relevant topic
  let bestTopic = '';
  let maxMatches = 0;

  for (const [topic, keywords] of Object.entries(topicKeywords)) {
    const matches = keywords.filter(keyword => text.includes(keyword)).length;
    if (matches > maxMatches) {
      maxMatches = matches;
      bestTopic = topic;
    }
  }

  // Extract key phrases from the text
  const words = text.split(' ').filter(word => word.length > 3);
  const keyWords = words.slice(0, 4); // Take first 4 meaningful words

  // Generate title based on topic and keywords
  if (bestTopic && maxMatches > 0) {
    const keyPhrase = keyWords.slice(0, 2).join(' ').replace(/[^\w\s]/g, '');
    return `${bestTopic}: ${capitalizeWords(keyPhrase)}`;
  }

  // Fallback: use first few words as title
  const fallbackTitle = keyWords.slice(0, 3).join(' ').replace(/[^\w\s]/g, '');
  return capitalizeWords(fallbackTitle) || 'New Chat';
}

/**
 * Capitalizes the first letter of each word
 * @param text Input text
 * @returns Text with capitalized words
 */
function capitalizeWords(text: string): string {
  return text
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Generates a session title using OpenAI API (more sophisticated)
 * @param messages Array of user messages
 * @param openaiApiKey Optional OpenAI API key
 * @returns Promise<string> A smart title generated by AI
 */
export async function generateSessionTitleWithAI(
  messages: string[], 
  openaiApiKey?: string
): Promise<string> {
  if (!openaiApiKey || !messages || messages.length === 0) {
    // Fallback to simple generation
    return generateSessionTitle(messages);
  }

  try {
    const { OpenAI } = await import('openai');
    const openai = new OpenAI({ apiKey: openaiApiKey });

    // Take first 3 messages and create a summary
    const firstMessages = messages.slice(0, 3);
    const combinedText = firstMessages.join('\n');

    const completion = await openai.chat.completions.create({
      model: 'gpt-3.5-turbo',
      messages: [
        {
          role: 'system',
          content: 'You are an assistant that creates short, descriptive titles for chat sessions. Generate a title that captures the main topic or theme of the conversation. Keep it under 50 characters and make it engaging and clear.'
        },
        {
          role: 'user',
          content: `Create a short title for this chat session based on these first few messages:\n\n${combinedText}\n\nReturn only the title, no other text.`
        }
      ],
      max_tokens: 20,
      temperature: 0.7,
    });

    const title = completion.choices[0]?.message?.content?.trim();
    return title || generateSessionTitle(messages);
  } catch (error) {
    console.error('Error generating AI title:', error);
    // Fallback to simple generation
    return generateSessionTitle(messages);
  }
} 